export const languages = [
  { id: "0", label: "Detect Language", value: "auto" },
  { id: "1", label: "Abkhaz", value: "ab" },
  { id: "2", label: "Acehnese", value: "ace" },
  { id: "3", label: "Acholi", value: "ach" },
  { id: "4", label: "Afar", value: "aa" },
  { id: "5", label: "Afrikaans", value: "af" },
  { id: "6", label: "Albanian", value: "sq" },
  { id: "7", label: "Alur", value: "alz" },
  { id: "8", label: "Amharic", value: "am" },
  { id: "9", label: "Arabic", value: "ar" },
  { id: "10", label: "Armenian", value: "hy" },
  { id: "11", label: "Assamese", value: "as" },
  { id: "12", label: "Avar", value: "av" },
  { id: "13", label: "Awadhi", value: "awa" },
  { id: "14", label: "Aymara", value: "ay" },
  { id: "15", label: "Azerbaijani", value: "az" },
  { id: "16", label: "Balinese", value: "ban" },
  { id: "17", label: "Baluchi", value: "bal" },
  { id: "18", label: "Bambara", value: "bm" },
  { id: "19", label: "Bashkir", value: "ba" },
  { id: "20", label: "Basque", value: "eu" },
  { id: "21", label: "Batak Karo", value: "btx" },
  { id: "22", label: "Batak Simalungun", value: "bts" },
  { id: "23", label: "Batak Toba", value: "bbc" },
  { id: "24", label: "Belarusian", value: "be" },
  { id: "25", label: "Bemba", value: "bem" },
  { id: "26", label: "Bengali", value: "bn" },
  { id: "27", label: "Betawi", value: "bew" },
  { id: "28", label: "Bhojpuri", value: "bho" },
  { id: "29", label: "Bikol", value: "bik" },
  { id: "30", label: "Bisaya", value: "ceb" },
  { id: "31", label: "Bosnian", value: "bs" },
  { id: "32", label: "Breton", value: "br" },
  { id: "33", label: "Bulgarian", value: "bg" },
  { id: "34", label: "Buryat", value: "bua" },
  { id: "35", label: "Cantonese", value: "yue" },
  { id: "36", label: "Catalan", value: "ca" },
  { id: "37", label: "Cebuano", value: "ceb" },
  { id: "38", label: "Chamorro", value: "ch" },
  { id: "39", label: "Chechen", value: "ce" },
  { id: "40", label: "Chichewa", value: "ny" },
  { id: "41", label: "Chinese", value: "zh-CN" },
  { id: "42", label: "Chinese Traditional", value: "zh-TW" },
  { id: "43", label: "Chuukese", value: "chk" },
  { id: "44", label: "Chuvash", value: "cv" },
  { id: "45", label: "Corsican", value: "co" },
  { id: "46", label: "Crimean Tatar", value: "crh" },
  { id: "47", label: "Croatian", value: "hr" },
  { id: "48", label: "Czech", value: "cs" },
  { id: "49", label: "Danish", value: "da" },
  { id: "50", label: "Dari", value: "fa-AF" },
  { id: "51", label: "Dhivehi", value: "dv" },
  { id: "52", label: "Dinka", value: "din" },
  { id: "53", label: "Dogri", value: "doi" },
  { id: "54", label: "Dombe", value: "dov" },
  { id: "55", label: "Dutch", value: "nl" },
  { id: "56", label: "Dyula", value: "dyu" },
  { id: "57", label: "Dzongkha", value: "dz" },
  { id: "58", label: "Egyptian Arabic", value: "arz" },
  { id: "59", label: "English", value: "en" },
  { id: "60", label: "Esperanto", value: "eo" },
  { id: "61", label: "Estonian", value: "et" },
  { id: "62", label: "Ewe", value: "ee" },
  { id: "63", label: "Faroese", value: "fo" },
  { id: "64", label: "Fijian", value: "fj" },
  { id: "65", label: "Filipino", value: "tl" },
  { id: "66", label: "Finnish", value: "fi" },
  { id: "67", label: "Fon", value: "fon" },
  { id: "68", label: "Francais", value: "fr" },
  { id: "69", label: "French", value: "fr" },
  { id: "70", label: "Friulian", value: "fur" },
  { id: "71", label: "Frisian", value: "fy" },
  { id: "72", label: "Fulani", value: "ff" },
  { id: "73", label: "Ga", value: "gaa" },
  { id: "74", label: "Galician", value: "gl" },
  { id: "75", label: "Georgian", value: "ka" },
  { id: "76", label: "German", value: "de" },
  { id: "77", label: "Greek", value: "el" },
  { id: "78", label: "Guarani", value: "gn" },
  { id: "79", label: "Gujarati", value: "gu" },
  { id: "80", label: "Haitian Creole", value: "ht" },
  { id: "81", label: "Hakha Chin", value: "cnh" },
  { id: "82", label: "Hausa", value: "ha" },
  { id: "83", label: "Hawaiian", value: "haw" },
  { id: "84", label: "Hebrew", value: "he" },
  { id: "85", label: "Hiligaynon", value: "hil" },
  { id: "86", label: "Hindi", value: "hi" },
  { id: "87", label: "Hmong", value: "hmn" },
  { id: "88", label: "Hungarian", value: "hu" },
  { id: "89", label: "Hunsrik", value: "hrx" },
  { id: "90", label: "Iban", value: "iba" },
  { id: "91", label: "Icelandic", value: "is" },
  { id: "92", label: "Igbo", value: "ig" },
  { id: "93", label: "Ilocano", value: "ilo" },
  { id: "94", label: "Indonesian", value: "id" },
  { id: "95", label: "Irish", value: "ga" },
  { id: "96", label: "Italian", value: "it" },
  { id: "97", label: "Jamaican Patois", value: "jam" },
  { id: "98", label: "Japanese", value: "ja" },
  { id: "99", label: "Javanese", value: "jw" },
  { id: "100", label: "Jingpo", value: "kac" },
  { id: "101", label: "Kalaallisut", value: "kl" },
  { id: "102", label: "Kannada", value: "kn" },
  { id: "103", label: "Kanuri", value: "kr" },
  { id: "104", label: "Kapampangan", value: "pam" },
  { id: "105", label: "Kazakh", value: "kk" },
  { id: "106", label: "Khasi", value: "kha" },
  { id: "107", label: "Khmer", value: "km" },
  { id: "108", label: "Kiga", value: "cgg" },
  { id: "109", label: "Kikongo", value: "kg" },
  { id: "110", label: "Kinyarwanda", value: "rw" },
  { id: "111", label: "Kituba", value: "ktu" },
  { id: "112", label: "Kokborok", value: "trp" },
  { id: "113", label: "Komi", value: "kv" },
  { id: "114", label: "Konkani", value: "gom" },
  { id: "115", label: "Korean", value: "ko" },
  { id: "116", label: "Krio", value: "kri" },
  { id: "117", label: "Kurdish Kurmanji", value: "ku" },
  { id: "118", label: "Kurdish Sorani", value: "ckb" },
  { id: "119", label: "Kyrgyz", value: "ky" },
  { id: "120", label: "Lao", value: "lo" },
  { id: "121", label: "Latgalian", value: "ltg" },
  { id: "122", label: "Latin", value: "la" },
  { id: "123", label: "Latvian", value: "lv" },
  { id: "124", label: "Ligurian", value: "lij" },
  { id: "125", label: "Limburgish", value: "li" },
  { id: "126", label: "Lingala", value: "ln" },
  { id: "127", label: "Lithuanian", value: "lt" },
  { id: "128", label: "Lombard", value: "lmo" },
  { id: "129", label: "Luganda", value: "lg" },
  { id: "130", label: "Luo", value: "luo" },
  { id: "131", label: "Luxembourgish", value: "lb" },
  { id: "132", label: "Macedonian", value: "mk" },
  { id: "133", label: "Madurese", value: "mad" },
  { id: "134", label: "Maithili", value: "mai" },
  { id: "135", label: "Makassar", value: "mak" },
  { id: "136", label: "Malagasy", value: "mg" },
  { id: "137", label: "Malay", value: "ms" },
  { id: "138", label: "Jawi", value: "ms-Arab" },
  { id: "139", label: "Malayalam", value: "ml" },
  { id: "140", label: "Maltese", value: "mt" },
  { id: "141", label: "Mam", value: "mam" },
  { id: "142", label: "Manx", value: "gv" },
  { id: "143", label: "Maori", value: "mi" },
  { id: "144", label: "Marathi", value: "mr" },
  { id: "145", label: "Marshallese", value: "mh" },
  { id: "146", label: "Marwadi", value: "mwr" },
  { id: "147", label: "Mauritian Creole", value: "mfe" },
  { id: "148", label: "Meadow Mari", value: "chm" },
  { id: "149", label: "Meiteilon Manipuri", value: "mni-Mtei" },
  { id: "150", label: "Minang", value: "min" },
  { id: "151", label: "Mizo", value: "lus" },
  { id: "152", label: "Mongolian", value: "mn" },
  { id: "153", label: "Myanmar Burmese", value: "my" },
  { id: "154", label: "Nahuatl Eastern Huasteca", value: "nhe" },
  { id: "155", label: "Ndau", value: "ndc-ZW" },
  { id: "156", label: "Ndebele South", value: "nr" },
  { id: "157", label: "Nepalbhasa Newari", value: "new" },
  { id: "158", label: "Nepali", value: "ne" },
  { id: "159", label: "NKo", value: "bm-Nkoo" },
  { id: "160", label: "Norwegian", value: "no" },
  { id: "161", label: "Nuer", value: "nus" },
  { id: "162", label: "Occitan", value: "oc" },
  { id: "163", label: "Odia", value: "or" },
  { id: "164", label: "Oromo", value: "om" },
  { id: "165", label: "Ossetian", value: "os" },
  { id: "166", label: "Pangasinan", value: "pag" },
  { id: "167", label: "Papiamento", value: "pap" },
  { id: "168", label: "Pashto", value: "ps" },
  { id: "169", label: "Persian", value: "fa" },
  { id: "170", label: "Polish", value: "pl" },
  { id: "171", label: "Portuguese Brazil", value: "pt" },
  { id: "172", label: "Portuguese Portugal", value: "pt-PT" },
  { id: "173", label: "Punjabi Gurmukhi", value: "pa" },
  { id: "174", label: "Punjabi Shahmukhi", value: "pa-Arab" },
  { id: "175", label: "Quechua", value: "qu" },
  { id: "176", label: "Qeqchi", value: "kek" },
  { id: "177", label: "Romani", value: "rom" },
  { id: "178", label: "Romanian", value: "ro" },
  { id: "179", label: "Rundi", value: "rn" },
  { id: "180", label: "Russian", value: "ru" },
  { id: "181", label: "Sami North", value: "se" },
  { id: "182", label: "Samoan", value: "sm" },
  { id: "183", label: "Sango", value: "sg" },
  { id: "184", label: "Sanskrit", value: "sa" },
  { id: "185", label: "Santali Latin", value: "sat-Latn" },
  { id: "186", label: "Scots Gaelic", value: "gd" },
  { id: "187", label: "Sepedi", value: "nso" },
  { id: "188", label: "Serbian", value: "sr" },
  { id: "189", label: "Sesotho", value: "st" },
  { id: "190", label: "Seychellois Creole", value: "crs" },
  { id: "191", label: "Shan", value: "shn" },
  { id: "192", label: "Shona", value: "sn" },
  { id: "193", label: "Sicilian", value: "scn" },
  { id: "194", label: "Silesian", value: "szl" },
  { id: "195", label: "Sindhi", value: "sd" },
  { id: "196", label: "Sinhala", value: "si" },
  { id: "197", label: "Slovak", value: "sk" },
  { id: "198", label: "Slovenian", value: "sl" },
  { id: "199", label: "Somali", value: "so" },
  { id: "200", label: "Spanish", value: "es" },
  { id: "201", label: "Sundanese", value: "su" },
  { id: "202", label: "Susu", value: "sus" },
  { id: "203", label: "Swahili", value: "sw" },
  { id: "204", label: "Swati", value: "ss" },
  { id: "205", label: "Swedish", value: "sv" },
  { id: "206", label: "Tagalog", value: "tl" },
  { id: "207", label: "Tahitian", value: "ty" },
  { id: "208", label: "Tajik", value: "tg" },
  { id: "209", label: "Tamazight", value: "ber-Latn" },
  { id: "210", label: "Tamazight Tifinagh", value: "ber" },
  { id: "211", label: "Tamil", value: "ta" },
  { id: "212", label: "Tatar", value: "tt" },
  { id: "213", label: "Telugu", value: "te" },
  { id: "214", label: "Tetum", value: "tet" },
  { id: "215", label: "Thai", value: "th" },
  { id: "216", label: "Tibetan", value: "bo" },
  { id: "217", label: "Tigrinya", value: "ti" },
  { id: "218", label: "Tiv", value: "tiv" },
  { id: "219", label: "Tok Pisin", value: "tpi" },
  { id: "220", label: "Tongan", value: "to" },
  { id: "221", label: "Tsonga", value: "ts" },
  { id: "222", label: "Tswana", value: "tn" },
  { id: "223", label: "Tulu", value: "tcy" },
  { id: "224", label: "Tumbuka", value: "tum" },
  { id: "225", label: "Turkish", value: "tr" },
  { id: "226", label: "Turkmen", value: "tk" },
  { id: "227", label: "Tuvan", value: "tyv" },
  { id: "228", label: "Twi", value: "ak" },
  { id: "229", label: "Udmurt", value: "udm" },
  { id: "230", label: "Ukrainian", value: "uk" },
  { id: "231", label: "Urdu", value: "ur" },
  { id: "232", label: "Uyghur", value: "ug" },
  { id: "233", label: "Uzbek", value: "uz" },
  { id: "234", label: "Venda", value: "ve" },
  { id: "235", label: "Venetian", value: "vec" },
  { id: "236", label: "Vietnamese", value: "vi" },
  { id: "237", label: "Waray", value: "war" },
  { id: "238", label: "Welsh", value: "cy" },
  { id: "239", label: "Wolof", value: "wo" },
  { id: "240", label: "Xhosa", value: "xh" },
  { id: "241", label: "Yakut", value: "sah" },
  { id: "242", label: "Yiddish", value: "yi" },
  { id: "243", label: "Yoruba", value: "yo" },
  { id: "244", label: "Yucatec Maya", value: "yua" },
  { id: "245", label: "Zapotec", value: "zap" },
  { id: "246", label: "Zulu", value: "zu" },
  { id: "247", label: "Santali Ol Chiki", value: "sat" },
  { id: "248", label: "Baoule", value: "bci" },
];

// Helper functions
export function getLanguageByValue(value: string) {
  return languages.find(lang => lang.value === value);
}

export function getLanguageBySlug(slug: string) {
  // Convert slug like "english" to find the language
  const normalizedSlug = slug.toLowerCase().replace(/-/g, ' ');
  return languages.find(lang => 
    lang.label.toLowerCase() === normalizedSlug ||
    lang.label.toLowerCase().replace(/\s+/g, '-') === slug.toLowerCase()
  );
}

export function slugifyLanguage(label: string) {
  return label.toLowerCase().replace(/\s+/g, '-');
}

export function unslugifyLanguage(slug: string) {
  return slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
