import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Disclaimer - AI Translation Accuracy',
  description: 'Disclaimer for our AI translation service. Translations are generated by AI and may not be 100% accurate. Verify important translations.',
  keywords: ['translation disclaimer', 'ai accuracy', 'translation accuracy', 'ai translate disclaimer', 'translation liability'],
}

export default function DisclaimerLayout({ children }: { children: React.ReactNode }) {
  return children
}
